@Library('olcne-pipeline@debugv4') _
import com.oracle.olcne.pipeline.BranchPattern

String version = "1.7.1";

olcnePipeline(
    branchPattern: new BranchPattern(master: "oracle/release/" + version, feature: '(?!^release/.*$)(^.*$)'),
    customStages: [container: [enabled: false]],
    platforms: ['ol8', 'ol9'],
    architectures: ['x86_64', 'aarch64'],
    goTidyVendor: true,
    preBuildCommands: ['unset GOPROXY'],
    yumOL8Repos:['ol8_appstream'],
    yumOL9Repos:['ol9_appstream']
)
